Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConFix.Models;

namespace eConFix.Controllers
{
    public class AdminsController : Controller
    {
        private ContextClass db = new ContextClass();

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userName,password")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index","Services");
            }

            return View(admin);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }





        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            if (ModelState.IsValid)
            {
                //Default admin login data
                if (admin.userName == "econfix" && admin.password == "econfix")
                {
                    //Access granted
                    return RedirectToAction("Index", "Services");
                }

                string username = admin.userName;
                string password = admin.password;
                admin = db.Admins.Find(admin.userName); 

                if (admin != null)
                {
                    if (admin.userName == username && admin.password == password)
                    {
                        //Access granted
                        return RedirectToAction("Index","Services");
                    }
                    ViewBag.feedback = "Invalid password!";
                    return View();
                }
                ViewBag.feedback = "Invalid email address!";
            }
            return View();
        }
    }
}

Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConFix.Models;

namespace eConFix.Controllers
{
    public class BookingsController : Controller
    {
        private ContextClass db = new ContextClass();

        // GET: Bookings
        public ActionResult Index()
        {
            try
            {
                //Feedback for booking exeptions
                if (TempData["error"]!=null)
                {
                    ViewBag.error = TempData["error"].ToString();
                }
                List<Booking> bookings = new List<Booking>();

                var list = (from b in db.Bookings
                            join r in db.Registers on b.emailAddress equals r.emailAddress
                            join s in db.Services on b.serviceId equals s.serviceId
                            select new { b.bookingId, r.name, s.serviceName, s.servicePrice }).ToList();

                foreach (var item in list)
                {
                    Booking obj = new Booking();
                    obj.bookingId = item.bookingId;
                    obj.emailAddress = item.name;
                    obj.service = item.serviceName;
                    obj.price = item.servicePrice;
                    bookings.Add(obj);
                }

                //Try login with saved cookies
                HttpCookie cookie = Request.Cookies["user"];
                if (cookie != null)
                {
                    //Check if the user still exists
                    if (db.Registers.Find(cookie.Value) != null)
                    {
                        ViewBag.userCookie = cookie.Value;
                        return View(bookings.ToList());
                    }
                    cookie.Expires = DateTime.Now;
                    Response.SetCookie(cookie);
                }

                HttpCookie session = Request.Cookies["session"];
                if (session != null)
                {
                    ViewBag.userCookie = session.Value;
                    return View(bookings.ToList());
                }
                return RedirectToAction("Login", "Registers");
            }
            catch (Exception)
            {
                return RedirectToAction("Login","Registers");
            }
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        public ActionResult Create()
        {
            try
            {
                HttpCookie cookie = Request.Cookies["user"];
                //Try login with saved cookies
                if (cookie != null)
                {
                    ViewBag.emailAddress = cookie.Value;
                    ViewBag.serviceId = new SelectList(db.Services, "serviceId", "serviceName");
                    ViewBag.servicePrice = new SelectList(db.Services, "serviceId", "servicePrice");
                    return View();
                }
                HttpCookie session = Request.Cookies["session"];
                Register register = db.Registers.Find(session.Value);

                ViewBag.emailAddress = register.emailAddress;
                ViewBag.serviceId = new SelectList(db.Services, "serviceId", "serviceName");
                ViewBag.servicePrice = new SelectList(db.Services, "serviceId", "servicePrice");
            }
            catch (Exception)
            {
                return RedirectToAction("Login","Registers");
            }
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "bookingId,emailAddress,serviceId,service,price")] Booking booking)
        {
            try
            {
                booking.service = booking.GetServiceName();
                booking.price = booking.GetPrice();
                if (booking.service != null && booking.price != 0)
                {
                    db.Bookings.Add(booking);
                    db.SaveChanges();
                    Models.eConFix eConFix = new Models.eConFix();
                    eConFix.SendMail(booking.emailAddress,"eConFix Booking","Booking",(Register)null,booking);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                if(ex.Message.Contains("Sequence contains no elements"))
                {
                    TempData["error"] = "All fields are required.";
                    return RedirectToAction("Index", "Bookings");
                }
                //Bookings Index feedback
                TempData["error"] = "Something went wrong!,  Try loging out and log back in.";
                return RedirectToAction("Index","Bookings");
            }

            ViewBag.emailAddress = new SelectList(db.Registers, "emailAddress", "name", booking.emailAddress);
            ViewBag.serviceId = new SelectList(db.Services, "serviceId", "serviceName", booking.serviceId);
            ViewBag.servicePrice = new SelectList(db.Services, "serviceId", "servicePrice");

            return View(booking);
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.emailAddress = new SelectList(db.Registers, "emailAddress", "name", booking.emailAddress);
            ViewBag.serviceId = new SelectList(db.Services, "serviceId", "serviceName", booking.serviceId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "bookingId,emailAddress,serviceId,price")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.emailAddress = new SelectList(db.Registers, "emailAddress", "name", booking.emailAddress);
            ViewBag.serviceId = new SelectList(db.Services, "serviceId", "serviceName", booking.serviceId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }









        ///
        ///
        ////////////////////////////////////////////////////
        ///

        public ActionResult Price(int? Id)
        {
            return View();
        }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eConFix.Models;

namespace eConFix.Controllers
{
    public class ServicesController : Controller
    {
        private ContextClass db = new ContextClass();

        // GET: Services
        public ActionResult Index()
        {
            return View(db.Services.ToList());
        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.Services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "serviceId,serviceName,servicePrice")] Services services)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(services);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(services);
        }

        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.Services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "serviceId,serviceName,servicePrice")] Services services)
        {
            if (ModelState.IsValid)
            {
                db.Entry(services).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(services);
        }

        // GET: Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.Services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Services services = db.Services.Find(id);
            db.Services.Remove(services);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////// P A R T I A L   V I E W S    A C T I O N S //////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        [ChildActionOnly]
        public PartialViewResult _Bookings()
        {
            //Return Partial view name and object
            return PartialView("_Bookings", db.Bookings.ToList());
        }
        [ChildActionOnly]
        public PartialViewResult _Admins()
        {
            //Return Partial view name and object
            return PartialView("_Admins", db.Admins.ToList());
        }
        [ChildActionOnly]
        public PartialViewResult _Registered()
        {
            return PartialView("_Registered", db.Registers.ToList());
        }













        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////// A D M I N  A C T I O N S ////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        public ActionResult DeleteMember(string emailAddress)
        {
            if (emailAddress!=null)
            {
                TempData["Id"] = emailAddress;
                return RedirectToAction("Delete","Registers");
            }
            return RedirectToAction("Index");
        }



        // GET: Admins/Delete/5
        public ActionResult DeleteAdmin(string userName)
        {
            Admin admin = db.Admins.Find(userName);
            db.Admins.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        // GET: Bookings/Delete/5
        public ActionResult DeleteBooking(int? id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Services/Create.cshtml
@model eConFix.Models.Services

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
    <link href="~/Content/Services/Create.css" rel="stylesheet" />
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Services</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.serviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.serviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.servicePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.servicePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.servicePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Services/Delete.cshtml
@model eConFix.Models.Services

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
    <link href="~/Content/Services/Delete.css" rel="stylesheet" />
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Services</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.serviceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.serviceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.servicePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.servicePrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Services/Details.cshtml
@model eConFix.Models.Services

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Services</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.serviceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.serviceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.servicePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.servicePrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.serviceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Services/Edit.cshtml
@model eConFix.Models.Services

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
    <link href="~/Content/Services/Edit.css" rel="stylesheet" />
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Services</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.serviceId)

        <div class="form-group">
            @Html.LabelFor(model => model.serviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.serviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.servicePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.servicePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.servicePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Services/Index.cshtml
@model IEnumerable<eConFix.Models.Services>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
    <link href="~/Content/Services/Index.css" rel="stylesheet" />
    <script src="~/Content/Services/Index.js"></script>
}

<style>
    body {
     
        
        background-position: inherit;
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("eConFix", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>
<h2>Administration page</h2>
@*<div>
    <ul>
        <li>@Html.ActionLink("Link", "")</li>
        <li>@Html.ActionLink("Link", "")</li>
        <li>@Html.ActionLink("Link", "")</li>
    </ul>
</div>*@


<div class="row">
    <div class="col-md-6">

        <h2>Offered services</h2>
        <div>
            <p>
                @Html.ActionLink("Add new service", "Create")
            </p>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.serviceName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.servicePrice)
                    </th>
                    <th>Actions</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.serviceName)
                        </td>
                        <td>
                            R @Html.DisplayFor(modelItem => item.servicePrice)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.serviceId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.serviceId })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
    <!--Admins list-->
    <div class="col-md-6">
        @Html.Action("_Admins")
    </div>
</div>

<div>
    <div class="col-lg-6">
        <!--Bookings list-->
        @Html.Action("_Bookings")
    </div>
    <div class="col-lg-6">
        @Html.Action("_Registered")
    </div>
</div>

Views/Services/_Admins.cshtml
@model IEnumerable<eConFix.Models.Admin>

<h2>Admins</h2>
<p>
    @Html.ActionLink("Add New", "Create","Admins")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @if (item.userName != "admin")
            {
                @Html.ActionLink("Delete Admin", "DeleteAdmin", new { userName = item.userName })
            }
        </td>
    </tr>
}

</table>

Views/Services/_Bookings.cshtml
@model IEnumerable<eConFix.Models.Booking>

<h2>Bookings</h2>

<table class="table" style="background-image: linear-gradient(45deg, #42687e59, #6d9dc733);padding:5px">
    <tr>
        <th>
            Customer name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.service)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Register.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.service)
        </td>
        <td>
            R @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.ActionLink("Delete", "DeleteBooking", new { id=item.bookingId })
        </td>
    </tr>
}

</table>

Views/Services/_Registered.cshtml
@model IEnumerable<eConFix.Models.Register>

<h2>Registered people</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.ActionLink("Delete", "DeleteMember", new { emailAddress = item.emailAddress })
        </td>
    </tr>
}

</table>